### ISSUE TITLE
Avoid trapping keyboard focus

### ISSUE THREAD

**Issue by binyamin** [jmjuanes/codecake#3]
This looks like an awesome project, and it's so small. Thanks for your work!

---

### Problem
Keyboard users traditionally use <kbd>tab</kbd> to move between focusable elements on a page. This poses an issue when dealing with code editors, because users also expect <kbd>tab</kbd> to indent their code.

### Solution
CodeMirror solves this by making <kbd>esc</kbd> <kbd>tab</kbd> move to the next focusable element, and <kbd>esc</kbd> <kbd>shift + tab</kbd> move to the previous focusable element. See https://codemirror.net/examples/tab/

See also [WCAG 2.1 Level A criterion for "No Keyboard Trap"](https://www.w3.org/TR/WCAG21/#no-keyboard-trap).

**Comment by jmjuanes** [comment]
Great point, thank you. I think we can solve this in the same way as CodeMirror.

> This looks like an awesome project, and it's so small. Thanks for your work!

Thank you so much! Hope you find it useful for your projects :smile:

**Comment by jmjuanes** [comment]
Fixed in https://github.com/jmjuanes/codecake/commit/99fd0065889cc770c1ef607eaa7f524c2b72644f. Thank you!!
